### ISSUE TITLE
[Modify] Segregate the API endpoints and controllers

### ISSUE THREAD

**Issue by kailash360** [kailash360/e-market#27]
## Is your modification request related to a problem? Please describe.

Currently the API endpoints and controllers are defined in the same file. This makes the file too large and difficult to debug.

## Describe the modification you'd like

They should be segregated and re-defined within a directory that stores the controllers classified on the basis of their purpose

## Additional context

NA

**Comment by Satyabrat-Ojha** [comment]
I would like contribute to the issue. Can you please assign it to me.

**Comment by kailash360** [comment]
Sure @Satyabrat-Ojha

**Comment by Satyabrat-Ojha** [comment]
Sir can you please mention the particular file or directory or can you share some resources to find it out myself

**Comment by codesmith25103** [comment]
@Satyabrat-Ojha  Are you working on this issue, if not, can I work on this issue?

**Comment by Satyabrat-Ojha** [comment]
@codesmith25103 yes I am working on it
