### ISSUE TITLE
[Modify] Shift the middleware into its individual directory

### ISSUE THREAD

**Issue by kailash360** [kailash360/e-market#28]
## Is your modification request related to a problem? Please describe.

Currently the middleware are defined in a single file in the root folder. 

## Describe the modification you'd like

Shift the middleware to a `middlewares` folder and classify them based on their purpose.

## Additional context

NA

**Comment by Aaroh1** [comment]
Hey @kailash360 ! Do I need to be assigned this issue before sending a PR? 
I've already sent a PR for the same.

**Comment by kailash360** [comment]
It is a good practice to get an issue assigned to yourself before you start working on it. This helps the other developers to understand that someone is working on that issue and does not create a conflict of work.

For now, I will consider your PR.
