### ISSUE TITLE
[Modify] Replace the favicon

### ISSUE THREAD

**Issue by kailash360** [kailash360/e-market#32]
## Is your modification request related to a problem? Please describe.

Currently, thee is no dedicated favicon for the pages.

## Describe the modification you'd like

A new favicon should be designed and added to the pages such that they align with the theme.

## Additional context

NA

**Comment by codesmith25103** [comment]
Sir, can you assign me this Issue?

**Comment by kailash360** [comment]
Sure @codesmith25103

**Comment by iamhariom0228** [comment]
hey @kailash360 , can you assign this to me?'
