### ISSUE TITLE
[Modify] Define the configurations in a separate directory

### ISSUE THREAD

**Issue by kailash360** [kailash360/e-market#33]
## Is your modification request related to a problem? Please describe.

Currently, the database configuration is defined in the driver file itself. This makes the configuration code redundant.

## Describe the modification you'd like

Ideally, there should be a segregated folder `config` which should store the different configurations for database and third-party integrations in the project.

## Additional context

Each configuration file should return a function which initializes the connection to the third party service. The function can then be called in the driver file.

**Comment by Aaroh1** [comment]
Hey @kailash360! Can you please assign this issue to me?

**Comment by Aaroh1** [comment]
Hey @kailash360! Any chance I can still work on this?

**Comment by kailash360** [comment]
Sure @Aaroh1
